# Generated by Django 5.0.8 on 2024-09-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
